### ISSUE TITLE
Confusing interface

### ISSUE THREAD

**Issue by jr2730** [DimensionDataResearch/ansible-modules-extras#5]
##### ISSUE TYPE

- Bug Report
- Feature Idea
##### COMPONENT NAME

dimensiondata_load_balancer.py
##### SUMMARY

The documentation states:

```
 listener_ip_address:
    description:
        - Must be a valid IPv4 in dot-decimal notation (x.x.x.x).
    required: true
    default: None
  provision_listener_ip_address:
    description:
      - Auto allocates a public IP address.
    required: true
    default: true
```

I think this is confusing and can lead to errors.
The current code:
- checks the boolean and (if true) allocates an IP address REGARDLESS of whether one was passed in or not.
- assumes that if the boolean is false, that an IP address is provided.   Strangely, that ends up succeeding (because the Create routine in the LB driver is only the IP address as its flag; it doesn't see an IP address so it allocates one).  HOWEVER, it is unclear if the Create routine allocates the same way that the get_unallocated_public_ips routine does.

I propose we drop the passed in boolean.

In this way, if you want to have the code auto provision an IP address, just don't provide one.
If you want to use your own IP address, then provide it.
Straight forward.

The NEW code should treat both None and an empty string as a request to provision a new IP address.

Tiny change but I think it makes it all so much more clear.
